extends:
  - plugin:@typescript-eslint/recommended
  - eye
parser: "@typescript-eslint/parser"
ignorePatterns:
  - lib
globals:
  JSX: true
rules:
  "@typescript-eslint/explicit-module-boundary-types":
    - off
  "@typescript-eslint/no-non-null-assertion":
    - off
  "@typescript-eslint/no-unused-vars":
    - warn
  "@typescript-eslint/no-redeclare":
    - error
    - ignoreDeclarationMerge: true
  "@typescript-eslint/quotes":
    - error
    - backtick
  no-unused-vars:
    - off
  no-redeclare:
    - off
  quotes:
    - off